### ISSUE TITLE
attribute generic.max_health effects continue after removing item

### ISSUE THREAD

**Issue by StoomGH** [White-145/item-editor#1]
I gave a chestplate +5 generic.max_health and was going to do the same for the rest of the armor set when I realized that the health remained after taking off the armor piece. It seems the effect does stop, but any health you've regenerated would remain. For example, if I had 5 bonus hearts and regenerated 2, then removed the armor, it would pretty much just be absorption hearts.

**Comment by White-145** [comment]
if you mean that regenerated hearts return when you put the armor back on, then this is not a bug. Health adjusts to current maximum health when taking damage, so these are not the same as absorption hearts. I haven't noticed any behavior different from this though, so please let me know if I misunderstood

**Comment by StoomGH** [comment]
No, the health will stay even if you remove the armor. If you stop holding the item/gaining health boost, the health will stop at wherever it was regenerated to

![image](https://github.com/White-145/item-editor/assets/146426949/cf51b2ae-62d2-4420-a123-a9a27450c3da)
![image](https://github.com/White-145/item-editor/assets/146426949/a4f4f978-048f-4d83-a387-7a8208190d90)
![image](https://github.com/White-145/item-editor/assets/146426949/36a62691-c532-4c74-9cfd-3bf426791038)

**Comment by White-145** [comment]
Strange. This doesn't happen to me. Do you have any other mods on?

**Comment by StoomGH** [comment]
Yes, these are the other mods I had on when I was using the editor. 
![image](https://github.com/White-145/item-editor/assets/146426949/59853664-f50e-4854-bfdf-a1e110360a83)

Also, sorry for the late reply. I completely forgot I posted this.

**Comment by White-145** [comment]
I didn't notice such behaviour myself, so I can't tell if it's a problem with this mod. In any way, this mod does not change anything about how attributes are applied, and if anything, it could be a minecraft's bug. If you can confirm that it's something in this mod that breaks stuff, open a new issue with the details.
