### ISSUE TITLE
Help me! (Fabric 1.20.6)

### ISSUE THREAD

**Issue by ivdsh1** [White-145/item-editor#5]
I have 2 questions:
- This mod is no longer working on servers, it used to work... is it a bug?
- How do I enchant an item with durability with this mod?

**Comment by White-145** [comment]
1. That's strange, it works fine for me (paper 1.20.6). Is it saying anything in game logs?
2. Not sure what do you mean. Do you mean enchanting item that has durability? Or changing its durability?

**Comment by ivdsh1** [comment]
I want to enchant an item with durability, but “durability” does not appear in “/edit enchantment”

**Comment by White-145** [comment]
If you want to change item's durability, use `/edit durability`

**Comment by ivdsh1** [comment]
And how do i add the durability enchantment to the item?

**Comment by ivdsh1** [comment]
ooooh, sorry lol, I was confused (It's just that in Brazil it's durability lol, sorry)

**Comment by ivdsh1** [comment]
Now about the first question, I tried to use /edit on a server belonging to a friend of mine, and it didn't work... (He had paper 1.20.4)

**Comment by White-145** [comment]
I'm not a server owner and don't know the details, but I think it may be caused by the big difference in item formats between 1.20.4 and 1.20.5-6. I'd suggest you to keep server and players on the ~same version, either by updating server to 1.20.6 or playing on 1.20.4 yourself

**Comment by ivdsh1** [comment]
Ok, tysm!
